### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by fukaoi** [fukaoi/crystal-ripple-sdk#4]
@y2k2mt

Done list

- [x] Fix  typo  ripple/payment.cr

Committed master blanch

**Comment by y2k2mt** [comment]
- When cloning `fukaoi/ripple-client-lib`, use `https` instead of `ssh`

**Comment by fukaoi** [comment]
- [ ] Reconnect wssocket

**Comment by fukaoi** [comment]
not found more issues, and closed
